services:
  redis-taskflow:
    image: "redis:7.0"
    container_name: "redis-taskflow"
    ports:
      - ${LOCAL_REDIS_HOST}:${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./backend/.env

  backend-taskflow:
    image: backend-taskflow:dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-taskflow"
    ports:
      - "8000:8000"
    volumes:
      - /Users/artemhaidei/Desktop/TaskFlow/taskflow/backend:/backend:ro
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env
    depends_on:
      - redis-taskflow

volumes:
  redis-data:
