services:
  redis:
    image: "redis:7.0"
    container_name: "redis-taskflow"
    ports:
      - ${LOCAL_REDIS_HOST}:${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./backend/.env

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local-redis:redis:${REDIS_PORT}
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - ./backend/.env

  backend:
    image: backend-taskflow:dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-taskflow"
    ports:
      - "8000:8000"
    volumes:
      - $(pwd)/backend:/backend:ro
    env_file:
      - ./backend/.env
    depends_on:
      - redis

volumes:
  redis-data:
