# Generated by Django 4.2.5 on 2023-10-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='if_description',
        ),
    ]
